---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:
# Knative creates 2 new annotations that cannot be modified
- path: [metadata, annotations, serving.knative.dev/creator]
  type: copy
  sources: [new, existing]
  resourceMatchers: &matchers
  - apiVersionKindMatcher: {apiVersion: serving.knative.dev/v1, kind: Service}

- path: [metadata, annotations, serving.knative.dev/lastModifier]
  type: copy
  sources: [new, existing]
  resourceMatchers: *matchers
