name: Checks after any release is published
on:
  release:
    types: ['published']

jobs:
  validate-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: kapp
          kapp: ${{ github.event.release.tag_name }}
      - run: |
          kapp version
          version=`kapp version`
          tag="${{ github.event.release.tag_name }}"
          tool_version="$(echo $version | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')"
          if [[ "v${tool_version}" == "${tag}" ]];
          then
            echo "Version match with $tag"
            exit 0
          else
            echo "Versions do not match v$tool_version != $tag"
            exit 1
          fi
